FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y git maven

RUN git clone https://github.com/phaeton87/boxfuse-sample-java-war-hello

WORKDIR /boxfuse-sample-java-war-hello
RUN mvn package